feat: #WB2-1759, add abondance frontend
OPEN-ENT-NG/wiki pull request #23
Opened 2024-06-27 15:27 UTC by Headan

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-07-02 15:52 UTC, ccreusat requested changes
voir commentaire @Headan

2024-07-02 15:52 UTC, ccreusat commented on frontend/src/routes/root/index.tsx
@Headan c'est pas bon. pourquoi avoir supprimer le loader ?

tu as repris ce qu'on a fait sur le mur collab, mais c'est particulier car on passait le Layout à 100% sans le header, etc.. dans le cadre de Wiki, on a pas besoin de faire ça :) 

- faut remettre le loader, basename, .. stp c'est pour la vérification des anciennes urls + redirection
- retirer l'usage de useLocation, headless..

2024-07-03 07:30 UTC, juniorode commented on backend/src/main/java/net/atos/entng/wiki/Wiki.java
> +        pluginClientPerCollection.put(PAGE_COLLECTION, IExplorerPluginClient.withBus(vertx, APPLICATION, PAGE_TYPE));
Est-ce que l'on veut vraiment indexer les pages des wikis ?

2024-07-03 07:39 UTC, david-cc commented on backend/src/main/java/net/atos/entng/wiki/Wiki.java
> +        pluginClientPerCollection.put(PAGE_COLLECTION, IExplorerPluginClient.withBus(vertx, APPLICATION, PAGE_TYPE));
c'est une bonne question :) je m'étais basé sur mur collab où on index les notes mais à voir pour le wiki ouai je sais pas ^^

2024-07-03 10:29 UTC, ccreusat commented
Ok pour moi @david-cc @Headan , reste à voir pour l'indexation

2024-07-03 12:15 UTC, david-cc commented on backend/src/main/java/net/atos/entng/wiki/Wiki.java
> +        pluginClientPerCollection.put(PAGE_COLLECTION, IExplorerPluginClient.withBus(vertx, APPLICATION, PAGE_TYPE));
ok vu avec Junior je vais enlever l'index pour les pages

2024-07-03 12:25 UTC, merged