feat: #WB2-1513, add treeview component in side bar with content
OPEN-ENT-NG/wiki pull request #27
Opened 2024-07-10 10:43 UTC by Headan

## Describe your changes
Ajout du composant TreeView dans la side bar à droite en récupérant les pages composant le wiki. 

Ticket : https://edifice-community.atlassian.net/browse/WB2-1513

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-07-10 13:45 UTC, ccreusat commented
@Headan sidebar à gauche ?

2024-07-10 13:48 UTC, Headan commented
> @Headan sidebar à gauche ?

Oui en effet j'ai confondu x)

2024-07-10 16:14 UTC, ccreusat requested changes

2024-07-10 16:14 UTC, ccreusat commented on frontend/src/store/index.ts
@Headan ce store devrait : 
- avoir son dossier
- tu peux le nommer treeview / treedata
- être importé comme l'était le store des droits dans le `index.ts` => il ne sert qu'à donc ne pas le remplacer 

initialement:

```
/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 This is a starter file and can be deleted.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 */
export * from './rights';
```

2024-07-10 16:14 UTC, ccreusat commented on frontend/src/routes/wiki/index.tsx
> +    setTreeData(
@Headan pour l'instant, rien ne fonctionne car le modèle `TreeNode[]` n'existe pas avec le composant. donc soit mettre la PR en Draft et revenir dessus une fois les évos sur le treeview de fait, et penser aux fonctions utilitaires sur la lib de composants.. mais là en l'état c'est NoGo ^^

2024-07-10 16:14 UTC, ccreusat commented on frontend/src/routes/wiki/index.tsx
> +  const treeData = useStoreContext((state) => state.treeData);
pas besoin de faire un selector de treeData vu que t'as déjà fait un hook dans le store `useTreeData` pour l'appeler directement :)

2024-07-10 16:16 UTC, ccreusat commented on frontend/src/store/index.ts
> +  setTreeData: (treeData: TreeNode[]) => set(() => ({ treeData })),
faire comme on avait fait sur l'explorer et séparer le state des actions => https://tkdodo.eu/blog/working-with-zustand#separate-actions-from-state

(faut que je pense à le faire sur le store des droits, mais je dois encore le revoir)

2024-07-10 16:33 UTC, Headan commented on frontend/src/routes/wiki/index.tsx
> +    setTreeData(
J'ai changé le model côté edifice-ui pour l'adapter et ca fonctionne plutot bien 👍

2024-07-12 13:21 UTC, ccreusat approved these changes

2024-07-12 13:21 UTC, merged