feat: #WB2-1523, add consult page with test
OPEN-ENT-NG/wiki pull request #38
Opened 2024-07-23 15:56 UTC by Headan

## Describe your changes

Ajout du composant consultation d'une page

## Checklist tests

## Issue ticket number and link

Ticket : https://edifice-community.atlassian.net/browse/WB2-1523

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [x] If it is a consequent feature, I have added thorough tests.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-07-24 15:21 UTC, ccreusat commented on backend/src/main/resources/i18n/fr.json
> +  "wiki.consul.author.avatar": "Avatar de l'auteur",
coquille dans la trad `wiki.consult` et pas `wiki.consul`

2024-07-24 15:21 UTC, ccreusat commented on backend/src/main/resources/i18n/fr.json
> +  "wiki.consul.author.avatar": "Avatar de l'auteur",
tu peux même mettre `read` à la place de `consult" (sur toutes les trads en consultation)

2024-07-24 15:22 UTC, ccreusat commented on frontend/src/features/wiki/ContentTitle.test.tsx
> +  const dataTestPage = {
y'a déjà un mock de page à réutiliser `mockPage`

2024-07-24 15:22 UTC, ccreusat commented on frontend/src/features/wiki/ContentTitle.tsx
je l'aurai plutôt nommer `ContentHeader`

2024-07-24 15:24 UTC, ccreusat commented on frontend/src/features/wiki/ContentTitle.tsx
> +    <div className="d-flex flex-column mt-8 mx-md-8">
`d-flex flex-column mt-24 ms-md-24 me-md-16`

2024-07-24 15:26 UTC, ccreusat commented on frontend/src/features/wiki/ContentTitle.tsx
> +    <div className="d-flex flex-column mt-8 mx-md-8">
avec la modif directement sur la route de consultation, pas besoin de `mt-8 mx-md-8`

2024-07-24 15:27 UTC, ccreusat commented on frontend/src/routes/page/index.tsx
> +    <div className="d-flex flex-column mt-8 mx-md-8">
mettre ça plutôt `d-flex flex-column mt-24 ms-md-24 me-md-16` pour respecter la maquette

2024-07-24 15:27 UTC, ccreusat commented on frontend/src/routes/page/index.tsx
> +        mode={'read'}
attention, pas besoin des `{}` en passant des string comme props!

2024-07-24 15:28 UTC, ccreusat commented on frontend/src/services/api/index.ts
> +      .get<PageArray>(`${baseURL}/${wikiId}/page/${pageId}`);
tu pouvais juste faire `Page[]` ici :)

2024-07-24 15:32 UTC, ccreusat commented on frontend/src/utils/AuthorUtils.ts
à voir si on externalise pas sur la lib `edifice-ui` car on va le retrouver partout.. autant les récupérer plus facilement avec un hook.. je vais y penser :)

2024-07-24 15:33 UTC, ccreusat commented on frontend/src/utils/AuthorUtils.ts
NB : faire un hook `useDirectory` et exporter les méthodes

2024-07-24 15:38 UTC, ccreusat requested changes
juste qqs changements, mais top!

2024-07-25 13:22 UTC, Headan commented on frontend/src/services/api/index.ts
> +      .get<PageArray>(`${baseURL}/${wikiId}/page/${pageId}`);
Du coup comme on reçoit Page maintenant. je l'ai modifié mais du coup je sais pas si c'est la solution car je sais pas si c'est bien ce qu'on doit recevoir :/

2024-07-25 13:28 UTC, ccreusat commented on frontend/src/services/api/index.ts
> +      .get<PageArray>(`${baseURL}/${wikiId}/page/${pageId}`);
si c'est bien `Page` qu'on doit recevoir , tu peux retirer `PageArray`

2024-07-25 13:51 UTC, merged