feat: #WB2-1592, add visible to revision creation
OPEN-ENT-NG/wiki pull request #48
Opened 2024-08-13 13:36 UTC by david-cc

## Describe your changes

Add isVisible property to page revision information and add some checks about updating a page and creating a revision based on specs : https://edifice-community.atlassian.net/wiki/spaces/ODE/pages/3830874113/Wiki+et+cours+2024+-+Documentation+fonctionnelle#G%C3%A9n%C3%A9rer-une-version

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-08-13 15:03 UTC, juniorode commented on backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
> +import io.netty.util.internal.StringUtil;
Il me semble que l'import est inutilisé.

2024-08-13 15:16 UTC, juniorode commented on backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
> +					// get existing page to compare page values
OK pour le traitement ci-dessous mais je pense que pour bien séparer les couches (controller, services, DAO) il faudrait mettre tout ça dans la méthode `updatePage`.

2024-08-13 15:18 UTC, juniorode requested changes
c.f. les commentaires

2024-08-13 15:25 UTC, david-cc commented on backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
> +import io.netty.util.internal.StringUtil;
yes en effet, j'enlève l'import

2024-08-13 15:30 UTC, david-cc commented on backend/src/main/java/net/atos/entng/wiki/controllers/WikiController.java
> +					// get existing page to compare page values
@juniorode il faudrait mettre tout le traitement dans la méthode `updatePage` du Service c'est ça ?

2024-08-14 07:19 UTC, juniorode approved these changes

2024-08-14 09:58 UTC, merged