Feat: #wb21878, display old html content
OPEN-ENT-NG/wiki pull request #93
Opened 2024-10-15 14:11 UTC by nabil-mansouri

## Describe your changes

Ce fix permet d'ajouter des 

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [X] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [X] If it is a consequent feature, I have added thorough tests.
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Any dependent changes have been added to this project (must specify in **Description**)

2024-10-16 08:20 UTC, ccreusat approved these changes

2024-10-16 11:15 UTC, juniorode commented on backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
> +									.put("contentPlain", transformedContent.getPlainTextContent());
Est-ce que vous en avez besoin ? côté blog c'était utilisé mais il me semble que ça ne l'est pas côté wiki

2024-10-16 11:15 UTC, juniorode commented on backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
> +									.set("pages.$.contentPlain", page.getString("contentPlain"))
idem ici

2024-10-16 11:17 UTC, juniorode requested changes
Il faudrait aussi :
- enlever le champ oldContent quand on fait une MàJ d'une page parce qu'on en aura plus besoin
- retirer le champ oldContent des champs remontés au front

2024-10-16 12:58 UTC, nabil-mansouri commented on backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
> +									.put("contentPlain", transformedContent.getPlainTextContent());
à priori pas nécessaire

2024-10-16 13:21 UTC, juniorode commented on backend/src/main/java/net/atos/entng/wiki/service/WikiServiceMongoImpl.java
> +			desiredFormats.add(ContentTransformerFormat.PLAINTEXT);
Si pas nécessaire alors on peut enlever ici aussi

2024-10-16 13:31 UTC, nabil-mansouri commented
> enlever le champ oldContent quand on fait une MàJ d'une page parce qu'on en aura plus besoin

Du coup dans updatePage j'ai ajouté le unset du champ

> retirer le champ oldContent des champs remontés au front

Dans coup j'ai retiré ce champs de toutes les projections (y compris celle pour les révisions) pour ne pas le retourner au front

2024-10-17 11:52 UTC, juniorode approved these changes

2024-10-17 12:04 UTC, merged